
---
format:
  html: {toc: true, toc-depth: 3, theme: cosmo, number-sections: false, output-file: assignments.hw3.q8.html}
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}
toc-title-numbers: false
number-depth: 0

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="assignments.hw3.q8_files/md-default0.js" type="text/javascript"></script><script src="assignments.hw3.q8_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns assignments.hw3.q8
  (:require
    [assignments.hw3.utils :refer :all]))
```
:::


## Question 8
---

#### *8) In 2024, Covid symptoms include running nose, cough, sore throat, fever, chills, body aches, and fatigue. An infected person may develop one or more symptoms simultaneously after three days. If the contaminated airborne particles and droplets spread randomly to four visitors sitting in a waiting room, what is the probability that all visitors developed at least one Covid-symptom after three days?*

To solve this problem, we need to model it as a probability distribution problem. We can think of this as distributing symptoms (or the virus) to the four visitors, where each visitor must receive at least one symptom.

This is similar to the occupancy problem we solved in Question 7, but with a twist: we don't have a fixed number of 'objects' (symptoms) to distribute. Instead, we need to consider the probability of each visitor developing at least one symptom independently.

Let's approach this step-by-step:

1. First, let's consider the probability of a single visitor developing at least one symptom.
2. Then, we'll calculate the probability of all four visitors developing at least one symptom.

For step 1:
- There are 7 possible symptoms.
- The probability of not developing a specific symptom is the complement of developing it.
- To not develop any symptom, a visitor must not develop each of the 7 symptoms.


::: {.sourceClojure}
```clojure
(def num-symptoms 7)
```
:::



::: {.sourceClojure}
```clojure
(defn probability-no-symptoms [p]
      (Math/pow (- 1 p) num-symptoms))
```
:::



::: {.sourceClojure}
```clojure
(defn probability-at-least-one-symptom [p]
      (- 1 (probability-no-symptoms p)))
```
:::


For step 2:
- All four visitors need to independently develop at least one symptom.
- This is the same as the probability of one visitor developing a symptom, raised to the power of 4.


::: {.sourceClojure}
```clojure
(defn probability-all-visitors-symptomatic [p]
      (Math/pow (probability-at-least-one-symptom p) 4))
```
:::


Now, let's calculate this probability for a range of p values, where p is the probability of developing each individual symptom:


::: {.sourceClojure}
```clojure
(def p-values [0.1 0.2 0.3 0.4 0.5])
```
:::



::: {.sourceClojure}
```clojure
(def probabilities-all-visitors
  (map (fn [p] {:p p :probability (probability-all-visitors-symptomatic p)})
       p-values))
```
:::



::: {.sourceClojure}
```clojure
(answer "Probabilities for all visitors developing at least one symptom:")
```
:::


> <span style="color: black; font-size: 1.5em;">**Probabilities for all visitors developing at least one symptom:**</span>


::: {.sourceClojure}
```clojure
(into [] probabilities-all-visitors)
```
:::



::: {.printedClojure}
```clojure
[{:p 0.1, :probability 0.07407875407434654}
 {:p 0.2, :probability 0.3900627838302041}
 {:p 0.3, :probability 0.7090879995682614}
 {:p 0.4, :probability 0.8926403161374201}
 {:p 0.5, :probability 0.9691143073141575}]

```
:::



::: {.sourceClojure}
```clojure
(doseq [p p-values]
       (println (str "For p = " p ", the probability that all visitors
  develop at least one symptom is approximately "
                     (format "%.4f" (probability-all-visitors-symptomatic
                                           p)))))
```
:::



::: {.printedClojure}
```clojure
nil

```
:::


**Interpretation:**

1. As the probability of developing each individual symptom (p) increases, the probability of all visitors developing at least one symptom increases rapidly.
2. Even with relatively low probabilities for individual symptoms, the chance of all four visitors showing symptoms can be quite high due to the multiple symptoms and visitors involved.
3. This demonstrates how easily a highly symptomatic disease can spread in a confined space like a waiting room.

**Sensitivity Analysis:**

Let's see how the result changes with the number of visitors:


::: {.sourceClojure}
```clojure
(defn probability-all-visitors-symptomatic-n [p n]
      (Math/pow (probability-at-least-one-symptom p) n))
```
:::



::: {.sourceClojure}
```clojure
(def probabilities-by-visitor-count
  (map (fn [n] {:visitors n :probability (probability-all-visitors-symptomatic-n 0.2 n)})
       (range 2 7)))
```
:::



::: {.sourceClojure}
```clojure
(answer "Probabilities for different numbers of visitors (p = 0.2):")
```
:::


> <span style="color: black; font-size: 1.5em;">**Probabilities for different numbers of visitors (p = 0.2):**</span>


::: {.sourceClojure}
```clojure
(into [] probabilities-by-visitor-count)
```
:::



::: {.printedClojure}
```clojure
[{:visitors 2, :probability 0.6245500651110398}
 {:visitors 3, :probability 0.49357242329626505}
 {:visitors 4, :probability 0.3900627838302041}
 {:visitors 5, :probability 0.308260689106696}
 {:visitors 6, :probability 0.24361373703854744}]

```
:::



::: {.sourceClojure}
```clojure
(doseq [n (range 2 7)]
       (let [p 0.2]                                         ; Let's fix p at 0.2 for this analysis
                 (println (str "For " n " visitors and p = " p ", the probability is approximately ")
                                       (format "%.4f" (probability-all-visitors-symptomatic-n p n)))))
```
:::



::: {.printedClojure}
```clojure
nil

```
:::


**Conclusion:**

This problem demonstrates the application of probability theory to epidemiology and public health. We've modeled the spread of Covid symptoms in a waiting room scenario, showing how individual probabilities of developing symptoms combine to affect group outcomes.

Key takeaways:
1. The probability of all visitors developing symptoms increases with both the individual symptom probability and the number of visitors.
2. Even with moderate individual probabilities, the chance of all members of a group showing symptoms can be high, especially in larger groups.
3. This kind of modeling is crucial for understanding disease spread and informing public health policies, especially in confined spaces like waiting rooms, classrooms, or public transportation.

In practice, more complex models would be used, accounting for factors like varying symptom probabilities, incubation periods, and individual susceptibilities. However, this simplified model provides valuable insights into the basic principles of disease spread probability.


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/adabwana/f24-m6410-hw3/blob/master/src/assignments/hw3/q8.clj">src/assignments/hw3/q8.clj</a></small></small></pre></div>
```
